In [1]:
import numpy as np

In [2]:
A = np.array([[3,-9],[2,4]])

In [3]:
print(A)

[[ 3 -9]
 [ 2  4]]


In [4]:
B= np.array([-42,2])

In [5]:
Z = np.linalg.solve(A, B)

In [6]:
print(Z)

[-5.  3.]


In [7]:
M=np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])

In [8]:
print(M)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [9]:
C=np.array([6,1,1])

In [10]:
y=np.linalg.solve(M,C)

In [12]:
print(y)

[ 3. -2.  1.]
